### ISSUE TITLE
[Question] Why do distribution integration tests have dependencies?

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1272]
I was looking over our tests manifest schema today and saw a `build-dependencies` node.  I was under the impression when we are running integration tests they are run against an OpenSearch service instance running the entire distribution.  Is this correct?

https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.0/opensearch-1.3.0-test.yml#L17-L23

```
  - name: anomaly-detection
    integ-test:
      build-dependencies:
        - job-scheduler
      test-configs:
        - with-security
        - without-security
```
