### ISSUE TITLE
[META] After tests are complete there should be a test-run manifest that allows for finding all related test artifacts

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1274]
### Problem
After integration tests are run there is alot of information on the standard out and a final summary message that looks like:
```
2021-11-22 22:39:29 INFO     | alerting             | with-security        | PASS  |    0 |
2021-11-22 22:39:29 INFO     | alerting             | without-security     | PASS  |    0 |
2021-11-22 22:39:29 INFO     | anomaly-detection    | with-security        | PASS  |    0 |
2021-11-22 22:39:29 INFO     | anomaly-detection    | without-security     | PASS  |    0 |
2021-11-22 22:39:29 INFO     | asynchronous-search  | with-security        | PASS  |    0 |
2021-11-22 22:39:29 INFO     | asynchronous-search  | without-security     | PASS  |    0 |
2021-11-22 22:39:29 INFO     | dashboards-reports   | without-security     | PASS  |    0 |
2021-11-22 22:39:29 INFO     | index-management     | with-security        | PASS  |    0 |
2021-11-22 22:39:29 INFO     | index-management     | without-security     | PASS  |    0 |
2021-11-22 22:39:29 INFO     | k-NN                 | with-security        | PASS  |    0 |
2021-11-22 22:39:29 INFO     | k-NN                 | without-security     | PASS  |    0 |
2021-11-22 22:39:29 INFO     | sql                  | with-security        | PASS  |    0 |
2021-11-22 22:39:29 INFO     | sql                  | without-security     | PASS  |    0 |
```

This is useful for humans, but harder for our automation systems to integrate with.  If we are going to automatically file bugs or analyze test results there is critical information missing such as how to look up service logs, or test result logs.

### Proposal 1: Create a test-run manifest / update component manifests

Rather than modify on this table based approach which is very useful for the happy path, I suggest we create a new test-run yml manifest.  The existing component manifest files would be augmented to include the hierarchy of all files under them for deep diving.

test-run manifest contents:
  - Exact command used to execute, for reproducabillity
  - Extracted details about the test circumstances
  - List of components (Same list as from [test-manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.0/opensearch-1.3.0-test.yml#L2))
    - Name of the component
    -  List configurations ran against that component
      - Name of the configuration
      - Arguments to the configuration
      - Test component manifest with additional and all associated artifacts
      - (Optional) the central report for investigation easy for a human to parse through

component manifest content [Existing implementation](https://github.com/opensearch-project/opensearch-build/blob/6ed1ce3c583233eae4fe1027969d778cfc7660f7/src/test_workflow/test_recorder/test_recorder.py#L40)
  - Existing contents: Name, exist code, test run, etc..
  - List of all files under the directory so they can be looked up.

#### test-run manifest located at  https://{BASE_URL}/test-results/test-run-b30b804a1a3e494089b720544627dd2e.yml
```
schema-version: '1.0'
test-run:
  Command: ./test.sh integ-test manifests/1.3.0/opensearch-1.3.0-test.yml https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/1032/linux/x64
  TestType: integ-test
  TestManifest: manifests/1.3.0/opensearch-1.3.0-test.yml
  DistributionManifest: https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/1032/linux/x64/dist/manifest.yml
  Product: OpenSearch
  TestId: b30b804a1a3e494089b720544627dd2e
components:
- name: asynchronous-search
  configs:
  - name: with-security
    pass: true
    report: https://{BASE_URL}/b30b804a1a3e494089b720544627dd2e/integ-test/asynchronous-search/with-security/test-results/opensearch-integ-test/index.html
    manifest: https://{BASE_URL}/b30b804a1a3e494089b720544627dd2e/integ-test/asynchronous-search/with-security/test-results/asynchronous-search.yml
  - name: without-security
    pass: true
    report: https://{BASE_URL}/b30b804a1a3e494089b720544627dd2e/integ-test/asynchronous-search/without-security/test-results/opensearch-integ-test/index.html
    manifest: https://{BASE_URL}/b30b804a1a3e494089b720544627dd2e/integ-test/asynchronous-search/without-security/test-results/asynchronous-search.yml
- name: alerting
  configs:
  - name: with-security
    pass: true
    manifest: https://{BASE_URL}/b30b804a1a3e494089b720544627dd2e/integ-test/alerting/with-security/test-results/alerting.yml
  - name: without-security
    pass: true
    manifest: https://{BASE_URL}/b30b804a1a3e494089b720544627dd2e/integ-test/alerting/with-security/test-results/alerting.yml
  ...
  ```

#### component outcome manifest located at https://{BASE_URL}/test-results/b30b804a1a3e494089b720544627dd2e/integ-test/alerting/with-security/alerting.yml
```
component_name: alerting
exit_code: 0
test_config: with-security
test_run_id: b30b804a1a3e494089b720544627dd2e
test_type: integ-test
files:
- https://{BASE_URL}/{COMPONT_PATH}/stderr.txt
- https://{BASE_URL}/{COMPONT_PATH}/stdout.txt
- https://{BASE_URL}/{COMPONT_PATH}/local-cluster-logs/stderr.txt
- https://{BASE_URL}/{COMPONT_PATH}/local-cluster-logs/stdout.txt
- https://{BASE_URL}/{COMPONT_PATH}/local-cluster-logs/opensearch-service-logs/opensearch.log
...
```

#### Re-path test results
It would be useful to reorganize the existing output to be slightly more collapsed as well, removing the `test-results` folder from the `component/config-name/test-results` path and placing the results within the `component/config-name` folder path.  We can look for other ways to make sure the data is very clear.  There might be other opportunities to improve the 'browsing experience'

#### Add correlating timestamps in stderr/stdout results
Not sure if this needs to be added as a wrapper of the console capturing code or if it would be better to change test.sh output from gradle to include these timestamps.  This is critical for aligning service failures against test execution when there isn't a clear output from a test failure.

### Action Items
- [x] https://github.com/opensearch-project/opensearch-build/issues/3382
- [x] https://github.com/opensearch-project/opensearch-build/issues/3381
- [x] #3499

**Comment by dblock** [comment]
I like this. I would only call out that most of the runs should be against artifacts on ci.opensearch.org and thus any test results should contain complete HTTPs links that work.

**Comment by peternied** [comment]
@ohltyler After the automation is running we will need something like this to make test results usable by everyone

**Comment by zelinh** [comment]
We would follow this approach for this issue.
Create a test-run manifest / update component manifests on Python workflow base 

The idea of this approach is to augment our current python test workflow, so the manifest generated could be also retrieved if we are running the code base locally. 
We want to generate a new manifest temporarily called test-run.yml generated after the integration tests run which would contains below contents:

* High level overview of the tests run and extracted details about the test circumstances.
    * Test Type (integ-test)
    * Test manifest used (manifests/2.5.0/opensearch-2.5.0-test.yml)
    * Type of the product tests run on
    * Version of the distribution.
    * General command to run the tests
    * Distribution manifest we run tests on. (URL or local URL path)
* List of components (Same list of components as from [test-manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.5.0/opensearch-2.5.0-test.yml)) 
    * Name of the component
    * Name of the configuration (with/without-security)
    * URL or local path to the test component manifest with additional information
    * Exact command used to execute, for reproducibility
    * List of all files under the directory so they can be looked up. e.g. standard output, standard error logs...

A sample `test-run.yml` could look like this
```
schema-version: '1.0'
test-run:
  Command: ./test.sh integ-test manifests/2.6.0/opensearch-2.6.0-test.yml --paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.6.0/7083/linux/x64/tar
  TestType: integ-test
  TestManifest: manifests/2.6.0/opensearch-2.6.0-test.yml
  DistributionManifest: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.6.0/7083/linux/x64/tar/dist/opensearch/manifest.yml
  Product: OpenSearch
  TestID: 2345
components:
- name: sql
  configs:
  - name: with-security
    status: pass
    logs:
    - https://ci.opensearch.org/ci/dbc/integ-test/2.6.0/7083/linux/x64/tar/test-results/2345/integ-test/sql/with-security/test-results/stderr.txt
    - https://ci.opensearch.org/ci/dbc/integ-test/2.6.0/7083/linux/x64/tar/test-results/2345/integ-test/sql/with-security/test-results/stdout.txt
    - https://ci.opensearch.org/ci/dbc/integ-test/2.6.0/7083/linux/x64/tar/test-results/2345/integ-test/sql/with-security/local-cluster-logs/stderr.txt
    - https://ci.opensearch.org/ci/dbc/integ-test/2.6.0/7083/linux/x64/tar/test-results/2345/integ-test/sql/with-security/local-cluster-logs/stdout.txt
  - name: without-security
    status: fail
    logs:
    - https://ci.opensearch.org/ci/dbc/integ-test/2.6.0/7083/linux/x64/tar/test-results/2345/integ-test/sql/without-security/test-results/stderr.txt
    - https://ci.opensearch.org/ci/dbc/integ-test/2.6.0/7083/linux/x64/tar/test-results/2345/integ-test/sql/without-security/test-results/stdout.txt
    - https://ci.opensearch.org/ci/dbc/integ-test/2.6.0/7083/linux/x64/tar/test-results/2345/integ-test/sql/without-security/local-cluster-logs/stderr.txt
    - https://ci.opensearch.org/ci/dbc/integ-test/2.6.0/7083/linux/x64/tar/test-results/2345/integ-test/sql/without-security/local-cluster-logs/stdout.txt
 ```

**Comment by zelinh** [comment]
With the new component yml file already implemented, we would now be starting on this `test-run` manifest which would include all of the plugins test results and attach the link/path to each of their component yml file. 

Sample test-run manifest: 
```
---
schema-version: '1.0'
name: OpenSearch
test-run:
  Command: ./test.sh integ-test manifests/2.7.0/opensearch-2.7.0-test.yml --paths
    opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.7.0/7771/linux/x64/tar
  TestType: integ-test
  TestManifest: manifests/2.7.0/opensearch-2.7.0-test.yml
  DistributionManifest: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.7.0/7771/linux/x64/tar/dist/opensearch/manifest.yml
  TestID: '2345'
components:
  - name: sql
    command: ./test.sh integ-test manifests/2.7.0/opensearch-2.7.0-test.yml --component
      sql --paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.7.0/7771/linux/x64/tar
    configs:
      - name: with-security
        status: pass
        yml: https://ci.opensearch.org/ci/dbc/integ-test/2.7.0/7771/linux/x64/tar/test-results/4967/integ-test/sql/with-security/sql.yml
      - name: without-security
        status: fail
        yml: https://ci.opensearch.org/ci/dbc/integ-test/2.7.0/7771/linux/x64/tar/test-results/4967/integ-test/sql/without-security/sql.yml
  - name: anomaly-detection
    command: ./test.sh integ-test manifests/2.7.0/opensearch-2.7.0-test.yml --component
      anomaly-detection --paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.7.0/7771/linux/x64/tar
    configs:
      - name: with-security
        status: pass
        yml: https://ci.opensearch.org/ci/dbc/integ-test/2.7.0/7771/linux/x64/tar/test-results/4967/integ-test/anomaly-detection/with-security/anomaly-detection.yml
      - name: without-security
        status: fail
        yml: https://ci.opensearch.org/ci/dbc/integ-test/2.7.0/7771/linux/x64/tar/test-results/4967/integ-test/anomaly-detection/without-security/anomaly-detection.yml
```
