### ISSUE TITLE
Build manifest to include JOB_NAME

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-build#1686]
### Is your feature request related to a problem? Please describe

Origin: https://github.com/opensearch-project/opensearch-build/pull/1653#discussion_r815728318

The name of the job that triggers `integ-test` pipeline along with the build ID is used to figure out which distribution to download and run tests against. This requires hardcoding that value.

### Describe the solution you'd like

I propose we include the job name with the build manifest. For example:
```
---
schema-version: '1.2'
build:
  name: OpenSearch Dashboards
  version: 2.0.0
  platform: linux
  architecture: x64
  distribution: tar
  id: '1417'
  job_name: 'distribution-build-opensearch-dashboards'
components:
  - name: OpenSearch-Dashboards
    repository: https://github.com/opensearch-project/OpenSearch-Dashboards.git
    ref: main
    commit_id: 7cb8297622788b7c074cea1f92e4c2ca9f8f5f5d
    artifacts:
      dist:
        - dist/opensearch-dashboards-min-2.0.0-linux-x64.tar.gz
    version: 2.0.0.0
  - name: functionalTestDashboards
    repository: https://github.com/opensearch-project/opensearch-dashboards-functional-test.git
    ref: main
    commit_id: 24fba9c0cf413db6c16ae4117d0502aae283a019
    version: 2.0.0.0

```

That way when passing the URL of the build manifest to the test job and downloading the manifest. I can get the value of `build.job_name` and pass that to run `runIntegTestScript`.

### Describe alternatives you've considered

An assumption could be that the URL passed is the same format `https://ci.opensearch.org/ci/dbc/**JOB_NAME**/1.3.0/latest/linux/arm64/builds/opensearch/manifest.yml`, and we can do the logic but we have access to the job name while building the build manifest and I think there are no guarantees that the format of this URL will stay the same.

Can also just pass another input in the jenkins params that takes the build job name.

### Additional context

I believe adding the job name to the build manifest could provide insight in the future if we have ever change the URLs or if a job was triggered and end up dumping the artifacts to another bucket that does not equal the expect name. Not sure if possible in the current system but if someone hard codes in the Playground it could happen.
