### ISSUE TITLE
Build manifest to include more CI information

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-build#1694]
### Is your feature request related to a problem? Please describe

Origin: https://github.com/opensearch-project/opensearch-build/pull/1653#discussion_r818139873

Currently the build manifest that gets published does not include any information of the docker image it should use. This would particular helpful when running automated testing when we need to know the appropriate image and would reduce the amount of inputs required for abstraction.

### Describe the solution you'd like

Build manifests to include the agent label and image so that when we download it in tests we can just access that information.

For example:
```
---
schema-version: '1.2'
build:
  name: OpenSearch Dashboards
  version: 2.0.0
  platform: linux
  architecture: x64
  distribution: tar
  id: '1417'
ci:
  agent: Jenkins-Agent-al2-x64-c54xlarge-Docker-Host
  image:
    name: opensearchstaging/ci-runner:centos7-x64-arm64-jdkmulti-node10.24.1-cypress6.9.1-20211028
components:
  - name: OpenSearch-Dashboards
    repository: https://github.com/opensearch-project/OpenSearch-Dashboards.git
    ref: main
    commit_id: 7cb8297622788b7c074cea1f92e4c2ca9f8f5f5d
    artifacts:
      dist:
        - dist/opensearch-dashboards-min-2.0.0-linux-x64.tar.gz
    version: 2.0.0.0
  - name: functionalTestDashboards
    repository: https://github.com/opensearch-project/opensearch-dashboards-functional-test.git
    ref: main
    commit_id: 24fba9c0cf413db6c16ae4117d0502aae283a019
    version: 2.0.0.0
```

This might require input manifests including agents for the different platforms and archs as well, but image is already available. for example:
```
---
schema-version: '1.0'
build:
  name: OpenSearch Dashboards
  version: 2.0.0
ci:
  agents: 
    - name: Jenkins-Agent-al2-x64-c54xlarge-Docker-Host
      platform: linux
      architecture: x64
   - name: Jenkins-Agent-al2-arm64-c6g4xlarge-Docker-Host
     platform: linux
     architecture: arm64
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-dashboards-build
components:
  - name: OpenSearch-Dashboards
    ref: main
    repository: https://github.com/opensearch-project/OpenSearch-Dashboards.git
    checks:
      - npm:package:version
  - name: functionalTestDashboards
    repository: https://github.com/opensearch-project/opensearch-dashboards-functional-test.git
    ref: main
```

### Describe alternatives you've considered

We could perhaps just add the agents just in the build manifest and get that information from Jenkins
