### ISSUE TITLE
Add a healthcheck capability (or include curl)

### ISSUE THREAD

**Issue by geoffharcourt** [opensearch-project/opensearch-build#2357]
### Is your feature request related to a problem? Please describe

We've been using Elasticsearch and are migrating to OpenSearch. One issue we've run into with OpenSearch 1.2.x is that we aren't able to healthcheck the OpenSearch instance launched from public Docker image.

With Elasticsearch 7.x we'd curl `localhost:9200` with this docker-compose setting:

```
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail 'localhost:9200/_cluster/health?wait_for_status=green&timeout=15s' || exit 1"]
      interval: 15s
      timeout: 15s
      retries: 12
```

However this doesn't work with OpenSearch's 1.2.4 image because `curl` isn't available. The 1.2.x docs even recomment using curl for checking if the container is up and healthy (https://opensearch.org/docs/1.2/opensearch/install/docker/#run-the-image). Without a healthcheck, CI jobs often start using OpenSearch before it's ready to accept data.

### Describe the solution you'd like

The ideal solution would be a script or command that could be run internally in the container so that docker-compose can report that it's ready for work. 

If that's not available, including `curl` or `wget` in the image would make it much easier for someone to roll their own healthcheck without needing to fork the image.

### Describe alternatives you've considered

For now we're using Elasticsearch 7 in CI as a stand-in for OpenSearch, which seems fine, but has less fidelity to what we plan to do in production.
