### ISSUE TITLE
[Bug]: Intermittent startup issues with Opensearch 1.3.3 Docker container

### ISSUE THREAD

**Issue by threesquared** [opensearch-project/opensearch-build#2568]
### Describe the bug

We are seeing intermittent but pretty regular issues when using the Opensearch docker image in CI. All we see in the logs for the docker-compose container output is:

```
opensearch_1 | Killing opensearch process 10
opensearch_1 | Killing performance analyzer process 11
```

This is even after enabling trace level logging with `rootLogger.level = trace` in the log4j2 config. The full docker-compose config is:

```
elasticsearch:
    image: public.ecr.aws/peakon/opensearch:1.3.3
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - bootstrap.memory_lock=true
      - 'OPENSEARCH_JAVA_OPTS=-Xms2G -Xmx2G'
    restart: always
    shm_size: 2gb
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./docker/log4j2.properties:/usr/share/opensearch/config/log4j2.properties
```

We are also extending the Opensearch image to remove the security plugin and add analysis-icu plugin and our image can be found on public ECR as `public.ecr.aws/peakon/opensearch:1.3.3`

```
FROM opensearchproject/opensearch:1.3.3

RUN /usr/share/opensearch/bin/opensearch-plugin install --batch --verbose analysis-icu \
    && /usr/share/opensearch/bin/opensearch-plugin remove --verbose opensearch-security
```

The container continues to run and after `exec`ing into it the logs directory contains some output from the performance analyser plugin with some errors like:

```
ERROR org.opensearch.performanceanalyzer.rca.RcaController - Error reading file /usr/share/opensearch/data/rca_enabled.conf
```

However simply running `opensearch` within the container works, but using the entrypoint script results in the same error. It seems to be something to do with the terminateProcesses function.  

We have found that removing `CHILD` from the line `trap terminateProcesses TERM INT EXIT CHLD` in the script allows Opensearch to start up.

### To reproduce

This issue is hard for us to reproduce locally but happens fairly regularly in our CI infrastructure. If there is anything else we can do to debug this or get some more information that would be extremely handy.

### Expected behavior

The docker image should start Opensearch or exit with some error in the logs

### Host / Environment

Docker version 20.10.17, build 100c701
