### ISSUE TITLE
[Discussion] Modify input manfiest yml schema and assemble workflow to support pre-installation of native plugins

### ISSUE THREAD

**Issue by joshpalis** [opensearch-project/opensearch-build#2849]
### Is your feature request related to a problem? Please describe

Now that the Job Scheduler project ownership has been transferred to the OpenSearch Core Extensibility Team, we and the community have made a decision to relocate Job Scheduler to native plugins [1]. This change will have an effect on how the full bundle of OpenSearch is assembled, since multiple plugins (ISM, AD, Reporting) have a dependency on Job Scheduler. 

Currently, the input build manifest includes Job Scheduler as a component[2], and this will be removed upon relocation. However, unless there is a mechanism to detect and pre-install native plugin dependencies, assembly of the aforementioned dependent plugins will fail. 

[1] https://github.com/opensearch-project/OpenSearch/issues/4218
[2] https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.4.0/opensearch-2.4.0.yml#L26

### Describe the solution you'd like

In order to support the assembly of the Job Scheduler dependent components, I propose modifications to the input manifest yml schema such that native plugins that other components depend on will also be included. Consequently, changes to the input manifest yml schema will necessitate changes to the bundle_OpenSearch assemble workflow, such that native plugins listed within the input manifest are pre-installed prior to the dependent components.

CC : @prudhvigodithi @peterzhuamazon Open to discussion on how best to handle these changes

**Comment by owaiskazi19** [comment]
Thanks for writing this up @joshpalis. How about including a flag named `depends_on` for the plugins such as ISM, AD which are dependent on Job Scheduler in the input manifest?
```yml
 - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    depends_on: ['Job-Scheduler']
    ref: '2.4'
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
```
While reading the input manifest we have to take into account the dependency and based on the flag we can either install or not the JS native plugin.

**Comment by prudhvigodithi** [comment]
Hey @owaiskazi19 something similar to what proposed [here](https://github.com/opensearch-project/opensearch-build/issues/441#issuecomment-1275192880) ?
Another way is to have new schema as following 
```
native_plugins:
- job-scheduler
- repository-s3
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: main
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:publish
      - gradle:properties:version
```      
@dblock @bbarani

**Comment by owaiskazi19** [comment]
Hey @prudhvigodithi. Looks like we are on the same line with the scheme [here](https://github.com/opensearch-project/opensearch-build/issues/441#issuecomment-1275192880). 

For the above schema, I don't have any strong opinion(totally fine with it). Only just that it will create a little complex manifest file which can be simplified by using the flag `depends_on`. Let me know WDYT.

**Comment by joshpalis** [comment]
Thanks @owaiskazi19 and @prudhvigodithi for your contributions for this discussion. I am partial to Owais' proposal for the modifications to the input manifest yml schema. The modifications would be simplified and it places the onus of responsibility for components to define the plugins that they are dependent on, making it clear which components are dependent on which native plugin.

**Comment by prudhvigodithi** [comment]
[Triage]: Hey @joshpalis what is the targeted release with job-scheduler as native plugin, we should time this right to unblock 3.0.0 development.

**Comment by bbarani** [comment]
@joshpalis I would recommend to target 2.6.0 release since this is technically a breaking change for the build and development process so we need to synchronize the effort between multiple teams. CC: @CEHENKLE @peterzhuamazon @minalsha

**Comment by joshpalis** [comment]
Sure, I am fine with targeting 2.6.0 release. I have no strong opinions against this. @minalsha is this alright with you?

**Comment by minalsha** [comment]
@bbarani  we are working closely with folks across different teams. I don't see why we need to push it out. Lets target for 2.5.0 and see where we land on 01/02/2023. cc @CEHENKLE @prudhvigodithi @joshpalis @dagneyb

**Comment by bbarani** [comment]
@minalsha Is there a need to rush this change soon? This is not a new feature for users rather more of a change to existing plugin installation. This change needs to be synchronized across multiple versions. The available resources are currently working on 1.3.7 release along with Windows support hence I would not prioritize this for 2.5.0 release.

**Comment by saratvemulapalli** [comment]
> @saratvemulapalli Will this change be done only for 2.x and 3.x version. I assume 1.x versions are not affected by this change. Can you please confirm?

@bbarani you are right. This change will only go out for 2.x and above. This will not impact any 1.x releases. Job Scheduler will still be supported with the same maven co-ordinates for 1.x.

**Comment by joshpalis** [comment]
@bbarani @prudhvigodithi The relocation of Job Scheduler to native plugins has been determined to be a breaking change due to the necessary `build.gradle` modifications for dependent plugins. In our efforts to adhere to semantic versioning, we have modified our approach to relocate Job Scheduler to native plugins. Please refer to the updated section of [this issue](https://github.com/opensearch-project/OpenSearch/issues/5310) for additional information. 

Moving forward, modifications to the input manifest yml schema will still be necessary. Rather than the 2.6.0 release,  support for the pre-installation of native plugins shall only be needed for OpenSearch 3.x and onwards.

CC: @saratvemulapalli @minalsha

**Comment by gaiksaya** [comment]
[Proposal] Posting one of the approach here:

In order to add JS as a native plugin, a new schema needs to be introduced. Open search consist of a number of native plugins. In this case, we choose to install just one as a part of the distribution which is job scheduler (maybe more in future). Hence the manifest needs to document it.

One way is to have a `type` as one of the component key in the schema. The type key can be mandatory and the components can be defined accordingly. The following types seems valid:

* min (eg: OpenSearch, OpenSearch Dashboards)
* lib (eg: common-utils)
* core-plugin (eg: job scheduler, discovery-ec2)
* plugin (eg: anomaly detection, alerting)
* client: (eg: opensearch-high-level-rest client) → Example for future, out of scope for now.

Each type will define how the component is installed.

The functionality to install components that are of type core-plugin needs to be added to the build system.
* Building JS: From build perspective since native plugins are already built with the core we do not need to build again.
* Dependent plugins: For plugins with job scheduler as a dependency, it can retrieved from core dependencies which will already be taken care by plugins itself. The dependency will be retrieved from core modules so from build side if min is present we should be good.
* Assembling the distribution: In case of assembling the distribution, the JS needs to be installed from core plugins and then proceed with other plugin installations. 
* Publishing: For publishing and stuff, since it’s a part of native plugin now, it will continue to publish under https://repo1.maven.org/maven2/org/opensearch/plugin/opensearch-job-scheduler/ 

From offline discussion looks like the move will be happen from 2.x version but enforced from 3.x due to breaking changes.
We can decide if we want the new manifest schema should be introduced from 2.x version. Since build repository does not follow branching strategy to build (maybe it should), for 2.x the `type` for job-scheduler can be a `plugin` and then starting 3.0 it can be of type `core-plugin` 

The new input manifest can look like below:
```yaml
---
schema-version: '1.1'
build:
  name: OpenSearch
  version: 3.0.0
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v2
    args: -e JAVA_HOME=/opt/java/openjdk-17
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: main
    type: min
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    type: lib
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    type: core-plugin
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    type: plugin
    ref: main
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-ml-plugin
   
```

@saratvemulapalli @joshpalis @owaiskazi19  @dblock @opensearch-project/engineering-effectiveness  let me know what do you think about this. More approaches and recommendations are welcomed.
Thanks!
