### ISSUE TITLE
[Bug]: OpenSearch randomly refuses to start on GitHub Actions with absolutely no error logs

### ISSUE THREAD

**Issue by arg** [opensearch-project/opensearch-build#3024]
### Describe the bug

In the CI workflow (GHA) we use OpenSearch 1.2.4. Sometimes it refuses to start. Also we can't even see any logs from it.

### To reproduce

Create a workflow with the following content:

```yml
name: ci

on:
  push:
    branches: [master]
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      opensearch:
         image: opensearchproject/opensearch:1.2.4 # we actually use our private custom image based on v1.2.4 where we just install mapper-murmur3 plugin
         ports:
           - "9200:9200"
         env:
           OPENSEARCH_JAVA_OPTS: "-Xms4096m -Xmx4096m"
           bootstrap.memory_lock: true
           discovery.type: "single-node"
           DISABLE_INSTALL_DEMO_CONFIG: true
           DISABLE_SECURITY_PLUGIN: true
           rootLogger.level: "DEBUG"
           logger.level: "DEBUG"
           logger._root: "DEBUG"
           logger.org.opensearch.index.reindex: "DEBUG"
           logger.org.opensearch.action: "DEBUG"
           logger.org.opensearch.action.admin.cluster.health: "DEBUG"
         options: >-
           --cap-add IPC_LOCK
           --ulimit nofile=65536:65536
           --ulimit memlock=-1:-1
           --restart always
    steps:
      # different sources suggest to tune system with sysctl for better OS stability
      - name: Configure environment
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      # this step should restart OpenSearch, wait for 20 seconds, then render OS container logs and check OS connectivity by making a request with curl
      - name: Restart OpenSearch
        run: |
          docker restart "${{ job.services.elastic.id }}"
          sleep 20
          docker logs "${{ job.services.elastic.id }}" 1>&2
          curl --output /dev/null --silent --head --fail 'http://localhost:9200'
      ...
```

### Expected behavior

OpenSearch service starts successfully.

### Host / Environment

GitHub Actions runner (Ubuntu 22.04)

### Additional context

As you may see in the "To reproduce" section, we added two extra GHA steps in attempt to fix OS service startup and also to at least be able to see some error logs. They didn't really help though: yes, in case of a normal successful startup we see nice debug logs (because of the increased verbosity) but when it refuses to start, we see nothing (see example log output below).

### Relevant log output

```shell
Run docker restart "e46b9cd3212fd41d3df13b3b6a4129bc4e90ab27e4fa998dd3f7d8b449b961df"
e46b9cd3212fd41d3df13b3b6a4129bc4e90ab27e4fa998dd3f7d8b449b961df
warning: ignoring JAVA_OPTS=-Xms4096m -Xmx4096m; pass JVM parameters via OPENSEARCH_JAVA_OPTS
Killing opensearch process 11                 <- killing OS by "docker restart"
Killing performance analyzer process 12
OpenSearch exited with code 143
Performance analyzer exited with code 143
[1]-  Terminated              "$@" "${opensearch_opts[@]}"
Killing opensearch process 10
Killing performance analyzer process 11
Error: Process completed with exit code 56.   <- curl reports error, OS is not running
```
