### ISSUE TITLE
Add new Test manifest to test all plugin compatibility with Segment Replication and Remote Store enabled enabled

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/opensearch-build#3653]
### Is your feature request related to a problem? Please describe

To check plugin compatibility with segment replication and remote store we need to add a new test manifest file similar to what we have [here](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.7.0/opensearch-2.7.0-segment-replication-test.yml). We need to have these segment replication and remote store compatibility checks with plugins running daily, so we can find bugs as soon as possible.

With every upcoming releases  2.9 and forward we need to have manifest file specific to segment replication and remote store. Instead of manually raising an issue for adding this manifest file for every release, may be we can add this as part/responsibility of a new release.

### Describe the solution you'd like

Similar to segrep manifest file we had for 2.7 release [here](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.7.0/opensearch-2.7.0-segment-replication-test.yml) we need something similar to this. 

To enable Segment Replication and Remote store we need to set/pass following additional configs in opensearch.yml file:

```
additional-cluster-configs:
        cluster.indices.replication.strategy: 'SEGMENT'
        opensearch.experimental.feature.remote_store.enabled: true
        cluster.remote_store.enabled:true
```
