### ISSUE TITLE
Verify dependencies between plugins in CI

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#441]
**Is your feature request related to a problem? Please describe.**

Coming from https://github.com/opensearch-project/opensearch-build/pull/414#discussion_r706329805, verify dependencies (versions of) between plugins. For example several plugins depend on job-scheduler.

**Comment by peternied** [comment]
[Triage] @dblock This looks resolved, please reopen if this isn't the case.

**Comment by dblock** [comment]
We check that plugins depend on the correct version of OpenSearch in https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/src/ci_workflow/ci_check_gradle_dependencies_opensearch.py. This issue is about similarly checking that the version of other dependencies is correct.

**Comment by zelinh** [comment]
[Triage] @dblock Are you still looking into this issue or do you have a plan to resolve this?

**Comment by dblock** [comment]
I am not looking into it, but I believe it's still a nice to have feature.

**Comment by prudhvigodithi** [comment]
We can have the build process to look for dependency logic (`depends_on`), something like as follows 

Manifest: opensearch-2.4.0.yml 
```
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 2.x
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: 2.x
    platforms:
      - linux
      - windows
    checks:
      - gradle:publish
      - gradle:properties:version
    depends_on:
      - OpenSearch
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: '2.x'
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
 ```

With `depends_on` logic, the build process should 1st build the `depends_on` component, example from above case it should start with `OpenSearch` and proceed to `common-utils`, if in any case if `OpenSearch` fails it shouldn't even build `common-utils` and directly go to `alerting`, since `alerting` does not have any `depends_on` condition it should continue to build.
This way the dependency is handled and other non dependent components does not fail because of some other component dependency failed, having this logic we can even on board all the plugins in one go to the manifest (build yaml) and need not raise any separate PR's.
