### ISSUE TITLE
[BUG] Windows bundle manifest is using \ not / in url location

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#4506]
[BUG] Windows bundle manifest is using \ not / in url location

See [manifest (1).txt](https://github.com/opensearch-project/opensearch-build/files/14502231/manifest.1.txt).

```
---
schema-version: '1.1'
build:
  name: OpenSearch Dashboards
  version: 2.12.0
  platform: windows
  architecture: x64
  distribution: zip
  location: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.12.0/7326/windows/x64/zip/dist/opensearch-dashboards/opensearch-dashboards-2.12.0-windows-x64.zip
  id: '7326'
components:
  - name: OpenSearch-Dashboards
    repository: https://github.com/opensearch-project/OpenSearch-Dashboards.git
    ref: '2.12'
    commit_id: 9ec9a677af5f28e5450926ce07e9d6c3273717a7
    location: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.12.0/7326/windows/x64/zip/builds/opensearch-dashboards/dist\opensearch-dashboards-min-2.12.0-windows-x64.zip
......
```

It is due to build manifest saving relative path as `dist\<>.zip` or `plugins\<>.zip` for windows. We cannot fix this on root as the manifest can be either local path based, or url based for official release through Jenkins.

Therefore, we need to fix the bundle_url_location.py directly.

Thanks.
