### ISSUE TITLE
[Bug]: Test Report logger broke for OpenSearch Dashboards.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#4943]
### Describe the bug

Coming from https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1411 and https://github.com/opensearch-project/opensearch-build/pull/4796 after adding the ci-groups changes for OSD tests, the test report logger for OSD tests shows as `not available` this is because of the component name is no longer as `OpenSearch-Dashboards`. 

Example the `OpenSearch-Dashboards-ci-group-6` the log is now generated with the URL link https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.16.0/7858/linux/arm64/tar/test-results/6200/integ-test/OpenSearch-Dashboards-ci-group-6/with-security/OpenSearch-Dashboards-ci-group-6.yml  and not as https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.16.0/7858/linux/arm64/tar/test-results/6200/integ-test/OpenSearch-Dashboards/with-security/OpenSearch-Dashboards.yml.

With this `not available` the same data is now indexed to the [Metrics Cluster](https://metrics.opensearch.org/_dashboards/app/dashboards?security_tenant=global#/view/21aad140-49f6-11ef-bbdd-39a9b324a5aa?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))&_a=(description:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',filters:!(('$state':(store:appState),meta:(alias:!n,controlledBy:'1721852613904',disabled:!f,index:'16f55f10-4977-11ef-8565-15a1562cd0a0',key:version,negate:!f,params:(query:'2.16.0'),type:phrase),query:(match_phrase:(version:'2.16.0'))),('$state':(store:appState),meta:(alias:!n,controlledBy:'1721852622195',disabled:!f,index:'23eb6520-4977-11ef-bbdd-39a9b324a5aa',key:component,negate:!f,params:(query:OpenSearch-Dashboards),type:phrase),query:(match_phrase:(component:OpenSearch-Dashboards)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',viewMode:view)) showing as `not available`
 
<img width="1414" alt="Screenshot 2024-08-13 at 11 29 28 AM" src="https://github.com/user-attachments/assets/3cfad8b4-250f-4411-8685-4a89d34fdec1">

### To reproduce

Here is the real sample data https://build.ci.opensearch.org/job/integ-test-opensearch-dashboards/6248/artifact/test-report.yml that has `Not Available`
```
components:
  - name: OpenSearch-Dashboards
    command: ./test.sh integ-test manifests/2.16.0/opensearch-dashboards-2.16.0-test.yml
      --paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.16.0/10150/windows/x64/zip
      opensearch-dashboards=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.16.0/7858/windows/x64/zip
      --component OpenSearch-Dashboards
    configs:
      - name: with-security
        status: Not Available
        yml: URL not available
        cluster_stdout:
          - https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.16.0/7858/windows/x64/zip/test-results/6248/integ-test/OpenSearch-Dashboards/with-security/local-cluster-logs/id-0/stdout.txt
          - https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.16.0/7858/windows/x64/zip/test-results/6248/integ-test/OpenSearch-Dashboards/with-security/local-cluster-logs/id-1/stdout.txt
        cluster_stderr:
          - https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.16.0/7858/windows/x64/zip/test-results/6248/integ-test/OpenSearch-Dashboards/with-security/local-cluster-logs/id-0/stderr.txt
          - https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.16.0/7858/windows/x64/zip/test-results/6248/integ-test/OpenSearch-Dashboards/with-security/local-cluster-logs/id-1/stderr.txt
      - name: without-security
        status: Not Available
        yml: URL not available
        cluster_stdout:
          - https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.16.0/7858/windows/x64/zip/test-results/6248/integ-test/OpenSearch-Dashboards/without-security/local-cluster-logs/id-2/stdout.txt
          - https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.16.0/7858/windows/x64/zip/test-results/6248/integ-test/OpenSearch-Dashboards/without-security/local-cluster-logs/id-3/stdout.txt
        cluster_stderr:
          - https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.16.0/7858/windows/x64/zip/test-results/6248/integ-test/OpenSearch-Dashboards/without-security/local-cluster-logs/id-2/stderr.txt
          - https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.16.0/7858/windows/x64/zip/test-results/6248/integ-test/OpenSearch-Dashboards/without-security/local-cluster-logs/id-3/stderr.txt
```

### Expected behavior

The generated test report for OpenSearch Dashboards should:

- Either for OpenSearch-Dashboards to have a sub-component level for each ci-group and then with the same flow showing with-security and without-security data. During indexing to metrics cluster update the indexer library ([publishIntegTestResults](https://github.com/opensearch-project/opensearch-build-libraries/blob/main/vars/publishIntegTestResults.groovy)) to accommodate this change.
- Instead of sub-component, treat each of the ci-group as an individual component and add it to the test manifest. This will ensure the ([publishIntegTestResults](https://github.com/opensearch-project/opensearch-build-libraries/blob/main/vars/publishIntegTestResults.groovy)) indexes as each component (Example `OpenSearch-Dashboards-ci-group-6` `OpenSearch-Dashboards-ci-group-5` etc) and creates visualizations to ensure the results of OpenSearch-Dashboards summarizes all ci-groups.
