### ISSUE TITLE
Add new smoke test section into test manifest schema

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#5126]
Subtask from https://github.com/opensearch-project/opensearch-build/issues/4551

A new `smoke-test` section should be added to the test manifest to specify which component were onboarded for smoke tests. 

It could be looked like this
```
components:
  - name: opensearch
    smoke-test:
      test-spec: opensearch.yml
  - name: alerting
    integ-test:
      ...
    bwc-test:
      ...
    smoke-test:
      test-spec: alerting.yml
  - ...
 ```

In the above example, `opensearch & alerting` are onboarded with smoke test. In the `test-spec` section, it would point to a component spec yaml file which specifies the API request path for the smoke tests to run on.
