### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by 719media** [opensearch-project/opensearch-build#5266]
### Describe the bug

Unable to run opensearchproject/opensearch on macbook m4

### To reproduce

use some vanilla default docker yml like

```
version: '3'
services:
  opensearch-node1: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: test-opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1 # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=somePasswordForTestingWhatever1!    # Sets the demo admin user password when using demo configuration, required for OpenSearch 2.12 and later
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: test-opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  opensearch-net:
```

(taken straight from docker docs)

run it, notice that java crashes:

```
2025-01-27 12:46:26 # A fatal error has been detected by the Java Runtime Environment:
2025-01-27 12:46:26 #
2025-01-27 12:46:26 #  SIGILL (0x4) at pc=0x0000ffff6bd3fc5c, pid=15, tid=16
2025-01-27 12:46:26 #
2025-01-27 12:46:26 # JRE version:  (21.0.5+11) (build )
2025-01-27 12:46:26 # Java VM: OpenJDK 64-Bit Server VM (21.0.5+11-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-aarch64)
2025-01-27 12:46:26 # Problematic frame:
2025-01-27 12:46:26 # j  java.lang.System.registerNatives()V+0 java.base@21.0.5
```

### Expected behavior

possible to run opensearch on macbook m4.
I have tested this with both macOS 15.2 and 15.3 (released today), both have same error.

### Host / Environment

MacBook M4, MacOS 15.3
Problem does not occur on MacBook M3 (using MacOS 15.3 as well)

### Relevant log output

```shell

```
