### ISSUE TITLE
Test-manifest should take care of test related configurations specific to each plugin

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#545]
**Is your feature request related to a problem? Please describe.**
Some plugins needs to have system related configurations (a directory for example) to run their integration tests. 
As of today we need to change and maintain our codebase to accommodate this requirements

**Describe the solution you'd like**
We need to take care of this at test_manifest level where all plugin related configuration is at one place. 
Something like

```
components:
  - name: index-management
    integ-test:
      test-configs:
        - with-security
        - without-security
      additional-cluster-configs:
        - “path.repo: /tmp/tmp_dir”
      shell-commands:
        - “mkdir /tmp/tmp_dir”
 ```
The above shell command should run on the test environment and satisfy the requirements for `additional-cluster-configs`

**Comment by dblock** [comment]
We don't need a configuration to contain arbitrary shell commands. Each test can do whatever it wants, and has tools to execute anything, so if any prep work needs to happen for the tests, it should go into the tests.

I recommend the following structure:

```yaml
components:
  - name: index-management
     integ-test:
      configs:
        tests:
          -with-security
          -without-security
        cluster:
          - x: y
```
