### ISSUE TITLE
[Bug]: The location specified in bundle-manifest (manifest.yml) are invalid

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#661]
### Describe the bug

A build manifest is bundled inside the OpenSearch bundle tarball (manifest.yml) which contains all the information about the components used to build the bundle. The bundle manifest contains a key `location` whose value is invalid for all components.

```
build:
  architecture: x64
  id: '317'
  location: https://ci.opensearch.org/ci/bundles/1.1.0/317/opensearch-1.1.0-linux-x64.tar.gz
  name: OpenSearch
  version: 1.1.0
components:
- commit_id: 15e9f137622d878b79103df8f82d78d782b686a1
  location: https://ci.opensearch.org/ci/builds/1.1.0/317/bundle/opensearch-min-1.1.0-linux-x64.tar.gz
  name: OpenSearch
  ref: '1.1'
  repository: https://github.com/opensearch-project/OpenSearch.git
```

### To reproduce

Download the bundle. Untar it and see the manifest.yml

Try accessing the location url to download individual component. It will give `Access Denied` error

### Expected behavior

The URLs should be valid. Each component should be downloadable from the given location url
