### ISSUE TITLE
[Feature] Create Build lock file and use it during the build process

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#675]
_Conceptually this feature is aligned with npm's [package-lock.json](https://docs.npmjs.com/cli/v6/configuring-npm/package-locks) or python's [pipfile.lock](https://realpython.com/pipenv-guide/#the-pipfilelock)._

Reproducing build issues can be difficult if OpenSearch-build or one of the branches has changed since an error has first occurred.  Its also hard to identify if a build has already been made already - there is an cron job that rebuilds often and is typically rebuilding components that have already been built.

A new system should check the current repository, and the state of the remote repositories much like the current workflow
[run_manifests.py](https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/src/run_manifests.py).

The new manifest would look similar to the distribution manifest, with notable omissions of `location`, `architecture`, `id`, a new section called `build-system` would also be added to track the build system and version details.

By running `diff` against this output, the build process could process if there was an update, or end early if it is not necessary.  Additional changes could be made to use this file as a way to lock the built version into place so that only the associated commits are checked out rather than based on the point in time when the git clone take place during the build.

Example build-snapshot.yml
```
build:
  name: OpenSearch
  version: 1.1.0
build-system:
- commit_id: d5966e1cd1e1fa8914d6f6fda3ea9a80ef63d8e6
  name: OpenSearch-build
  ref: 'main'
  repository: https://github.com/opensearch-project/opensearch-build.git
components:
- commit_id: 15e9f137622d878b79103df8f82d78d782b686a1
  name: OpenSearch
  ref: '1.1'
  repository: https://github.com/opensearch-project/OpenSearch.git
- commit_id: 0a4ce10a812165e95801b77ede689064ffee2188
  name: job-scheduler
  ref: '1.1'
  repository: https://github.com/opensearch-project/job-scheduler.git
```

Example schema:
```
{
    "build": {
        "required": true,
        "type": "dict",
        "schema": {
            "name": {"required": true, "type": "string"},
            "version": {"required": true, "type": "string"}
        }
    },
    "schema-version": {"required": true, "type": "string", "allowed": ["1.0"]},
    "build-system": {
        "commit_id": {"required": true, "type": "string"},
        "name": {"required": true, "type": "string"},
        "ref": {"required": true, "type": "string"},
        "repository": {"required": true, "type": "string"}
    },
    "components": {
        "required": true,
        "type": "list",
        "schema": {
            "type": "dict",
            "schema": {
                "commit_id": {"required": true, "type": "string"},
                "name": {"required": true, "type": "string"},
                "ref": {"required": true, "type": "string"},
                "repository": {"required": true, "type": "string"}
            }
        }
    }
}
```
