### ISSUE TITLE
Add platform selection into components

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#811]
### Is your feature request related to a problem? Please describe

Coming from https://github.com/opensearch-project/opensearch-build/pull/809#discussion_r736732442, we had to create two manifests, one for windows and another for linux, to exclude a component from windows.

### Describe the solution you'd like

 add a way to include a plugin for certain platforms only.

```yaml
components:
  - name: k-nn
     platforms:
       - linux
       - darwin
```

Merge the existing manifests.
